"""Function-calling tools for the StoreUp Live session."""

from __future__ import annotations

import json
import time
from typing import Any, Optional, Sequence

from google.genai import types

from .product_store import VALID_CATEGORIES, store

_ADD_PRODUCT = types.FunctionDeclaration(
    name="add_product",
    description=(
        "Add a confirmed product to the store inventory. Call ONLY after the "
        "shopkeeper has verbally confirmed the product name, price, and quantity."
    ),
    parameters=types.Schema(
        type=types.Type.OBJECT,
        properties={
            "product_name": types.Schema(
                type=types.Type.STRING,
                description="Full product name with brand and variant (e.g. 'Maggi Masala Noodles 70g')",
            ),
            "price_inr": types.Schema(
                type=types.Type.NUMBER,
                description="Price per unit in Indian Rupees",
            ),
            "quantity": types.Schema(
                type=types.Type.INTEGER,
                description="Number of units in stock",
            ),
            "category": types.Schema(
                type=types.Type.STRING,
                enum=sorted(VALID_CATEGORIES),
                description="Product category",
            ),
        },
        required=["product_name", "price_inr", "quantity", "category"],
    ),
)

_GENERATE_STORE_DESCRIPTION = types.FunctionDeclaration(
    name="generate_store_description",
    description=(
        "Generate a compelling store description based on the conversation. "
        "Call after all products are added and before publishing."
    ),
    parameters=types.Schema(
        type=types.Type.OBJECT,
        properties={
            "store_name": types.Schema(type=types.Type.STRING, description="Name of the store"),
            "location": types.Schema(type=types.Type.STRING, description="Store location/area"),
            "description": types.Schema(type=types.Type.STRING, description="Optional description text generated by you"),
        },
        required=["store_name"],
    ),
)

_PUBLISH_STORE = types.FunctionDeclaration(
    name="publish_store",
    description=(
        "Finalize and publish the store catalog to ONDC. Call only after the "
        "shopkeeper has reviewed and confirmed the complete product list."
    ),
    parameters=types.Schema(
        type=types.Type.OBJECT,
        properties={
            "store_name": types.Schema(type=types.Type.STRING, description="Name of the store"),
            "store_location_gps": types.Schema(type=types.Type.STRING, description="GPS coordinates if available"),
        },
        required=["store_name"],
    ),
)


def get_tools(*, enable_search: bool = True) -> list[types.Tool]:
    tools: list[types.Tool] = [
        types.Tool(function_declarations=[_ADD_PRODUCT, _GENERATE_STORE_DESCRIPTION, _PUBLISH_STORE])
    ]
    if enable_search:
        tools.append(types.Tool(google_search=types.GoogleSearch()))
    return tools


_DEBOUNCE_SECONDS = 3.0
_last_calls: dict[str, float] = {}


def _is_duplicate(name: str, args: dict) -> bool:
    key = f"{name}:{json.dumps(args, sort_keys=True, default=str)}"
    now = time.time()
    prev = _last_calls.get(key)
    _last_calls[key] = now
    return prev is not None and (now - prev) < _DEBOUNCE_SECONDS


def execute(name: str, args: Optional[dict] = None) -> dict:
    args = args or {}
    if _is_duplicate(name, args):
        return {"status": "duplicate_ignored"}
    if name == "add_product":
        return store.add_product(
            product_name=args.get("product_name", ""),
            price_inr=float(args.get("price_inr", 0) or 0),
            quantity=int(args.get("quantity", 0) or 0),
            category=args.get("category", "Other"),
        )
    if name == "generate_store_description":
        return store.set_description(
            store_name=args.get("store_name", ""),
            location=args.get("location"),
            description=args.get("description"),
        )
    if name == "publish_store":
        return store.publish(
            store_name=args.get("store_name", ""),
            gps=args.get("store_location_gps"),
        )
    return {"status": "error", "error": f"unknown function '{name}'"}


def build_function_responses(function_calls: Sequence[Any]) -> list[types.FunctionResponse]:
    responses: list[types.FunctionResponse] = []
    for fc in function_calls:
        result = execute(fc.name, fc.args)
        responses.append(types.FunctionResponse(id=fc.id, name=fc.name, response=result))
    return responses
